---
title: "Hada_lymphocyte"
author: "Peter Wang"
date: "February 8, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(deSolve) # package for solving differential equations
library(minpack.lm) # package for non-linear regression #rks to laz: I think we probably can just use nls() in stats, not nlsLM from linpack. Please check in R documentation if there is any functional difference at all
library(mvtnorm) #package for calculating confidence intervals by Monte Carlo simulation based on variance-covariance matrices #rks to laz: I added to comment.Please check that my addition is OK.
rm(list=ls())
```

##Entering Data
```{r}
#Create dataframes that store the fibroblast WGE simple CA data used in 16Cacao 
#L and Z.b are rounded to the nearest 5.
Oxygen = data.frame(d = c(0, .0125, .025, .05, .075, .1, .2, .3, .4, .8),CA = c(.72, .96, 2.83, 4.7, 4.01, 8.41, 16.8, 40, 42.8, 94.4), ion = "O", Z = 8, L = 75, Z.b = 595)# Some GCR components are high-speed Oxygen nuclei that are almost fully ionized. d=dose; CA are per hundred cells. Z=atomic charge; L=LET; Z.b = Z^2/beta*^2

Si = data.frame(d = c(0, .02, .04, .06, .08, .1, .12, .15, .2, .3, .4, .6, .8, 1, 1.2, 1.5), CA = c(1.08, 2.04, 3.83, 4.57, 5.96, 4.78, 5.48, 13.88, 13.14, 27.0, 25.9, 59.5, 36.8, 81.8, 117.8, 123.2), ion = "Si", Z = 14, L = 100, Z.b = 690)

Fe600 = data.frame(d = c(0, 0.005, .01, .02, .04, .07, .1, .15, .2, .3, .4, .6, 1, 1.5), CA = c(1.01, 2.05, 2.33, 3.9, 3.51, 3.27, 5.71, 10.7, 9.14, 12.2, 21, 24.9, 43.6, 93.9), ion = "Fe600", Z = 26, L = 175, Z.b = 1075) #600 refers to the energy in MeV per atomic mass unit in this Iron beam

big_df = rbind(Oxygen, Si, Fe600)
big_df$error = c(.42, .48, 1.16, 1.36, 0.94, 2.54, 2.65, 5.9, 6.85, 13.6, .21, .34, .70, .95, .68, 1.07, 1.04, 2.38, 1.72, 4.77, 0.87, 9.18, 2.75, 9.85, 17, 13.2, 0.43, 0.48, 0.67, 0.8, 0.73, 0.75, 1.72, 1.95, 2.89, 2.34, 4.37, 5.08, 8.25, 18.8) #error bars for the CA measurementsx

#Next modify the data frame to get rid of the zero dose points. Background CA frequency was determined seperately.
modified_df = big_df[big_df$d != 0, ]
modified_df$CA = modified_df$CA*0.01 #Change it into per cell from per 100 cells
modified_df$error = modified_df$error*0.01
big_df$CA = big_df$CA * 0.01
big_df$error = big_df$error * 0.01
big_df$errorbar_lower = big_df$CA - big_df$error
big_df$errorbar_upper = big_df$CA + big_df$error

```

##NTE Functions for Lymphocytes
Not sure if this is needed anymore. Have lots of questions here
```{r}
#NTE1 and NTE2 models in 16Cacao using their parameters. NTE is used in 16Cacao to signify that non-targeted effects are included in the model; Conventional targeted effects (TE) are included in all models.
#NTE1 function
eta1 <- -0.75
lambda1 <- 40.3
eta2 <- 1.47
lambda2 <- 71
NTE1_function = function(d, L, Z.b, eta0 = 0.00011, eta1 = 0.007, sig0 = 6.12, kap = 796) {
  0.0017 + eta0*L*exp(-eta1*L)*(d != 0) + 
    (6.242*(d/L))*(sig0*(1-exp(-Z.b/kap))^2 + 0.041/6.24*L*(1 - (1-exp(-Z.b/kap))^2))
} 

#NTE2 function
NTE2_function = function(d, L, Z.b, eta0 = 0.00047, eta1 = 0.011, sig0 = 6.75, kap = 590) {
  0.0017 + eta0*L*exp(-eta1*L)*exp(-(1012*(d/L)))*(d != 0) + 
    (6.242*(d/L))*(1-exp(-(1012*(d/L))))*
    (sig0*(1-exp(-Z.b/kap))^2 + 0.041/6.24*L*(1 - (1-exp(-Z.b/kap))^2))
}
```

##Our IDER function
```{r}
#Our IDERs (Individual Dose Effect Relations). Applicable to the 1-ion components of a mixed simulated GCR beam 
#Modifying NTE1 and NTE2 by insisting they be twice continuously differentiable and monotonic increasing. Double check NTE1, NTE2, Our model
IDER = function(d, L, Z.b, eta0, eta1, sig0, kap) {
  P = (1-exp(-Z.b/kap))^2
  sig = sig0*P + 0.041/6.24*L*(1-P) # 0.041 +- 0.0051 comes from 16Cacao
  eta = eta0*L*exp(-eta1*L)
  0.00071 + sig*6.24*d/L*(1-exp(-1024*d/L)) + eta*(1-exp(-10^5*d))  #0.00071 + sig*6.24*d/L*(1-exp(-1024*d/L)) + eta*(1-exp(-10^3*d))#don't use
} 

#nls (non-linear least square) method to get the parameters needed (4 parameter estimation) #rks to laz: see note under issues
IDER_model = nlsLM(CA ~ IDER(d, L, Z.b, eta0, eta1, sig0, kap), data = modified_df, start = list(eta0 = 0.001, eta1 = 0.01, sig0 = 5, kap = 500), 
                   weights = (1/(modified_df$error)^2))

summary(IDER_model, correlation = T)
```

As expected, the eta's are not significant, but sig0 is, which indicates a linear model.