---
title: "NTE Simulation"
author: "Julien YU"
date: "2017/9/28"
output: html_document
---

```{r, echo = TRUE}
library(minpack.lm)

# Take cGy as the unit of dose; % as the unit of CA effect. 
# Assume the slope near origin to be ten times the slope afterwards. 
# Set m1 = 1; m2 = 0.1; d0 = 1; alpha = 1; E_star=m1*d0=1. 
# m1>>m2, d0 should be multiple of 0.1. 
m1 = 1
m2 = 0.1
E = 1
xmax = 100
Y0 = 0.001
dose = seq(0, 100, 0.1)
CA1 = seq(0, E, m1/10)
CA2 = seq(E + m2/10, (m1-m2)*E/m1 + 100*m2, m2/10)
f_NTE1 = function(d, m1, m2, E){E + m2*(d - E/m1)}
CA_NTE1 = c(CA1, CA2) + Y0
plot(dose, CA_NTE1, main = "Dose-Effect Relationship (NTE1)", xlab = "dose /cGy", ylab = "CA /%", pch = 18, xlim = c(0, xmax))
```

```{r, echo = TRUE}
# Now introduce NTE2. (Weighted average of NTE1 and an exponential curve)
f = function(d){E*exp((E/m1-d))}
# Get the NTE2 function for calibration (d > d0)
f_NTE2 = function(d, m1, m2, E){E*exp((E/m1-d))+m2*(d-E/m1)}
dose_mod = seq(m1 + m2, 100, 0.1)
CA3 = f(dose_mod)
CA_NTE2 = c(CA1, CA3+CA2-E) + Y0
plot(dose, CA_NTE2, main = "Dose-Effect Relationship (NTE2)", xlab = "dose /cGy", ylab = "CA /%", pch = 18, xlim = c(0, xmax))
```

```{r, echo = TRUE}
# Now introduce IDER. (concave & smooth curve around origin)
# Simulate with quadratic curve whose slope is m2 at d0. 
a = (m2*E/m1 - E)*(m1^2)/(E^2)
b = -m2 + 2*m1
f_IDER = function(d){a*d^2 + b*d}
dose2_mod = seq(0, E/m1, 0.1)
CA4 = f_IDER(dose2_mod)
CA5 = seq(f_IDER(E/m1) + m2/10, f_IDER(E/m1) + (100-E/m1)*m2, m2/10)
CA_IDER = c(CA4, CA5) + Y0
plot(dose, CA_IDER, main = "Dose-Effect Relationship (IDER)", xlab = "dose /cGy", ylab = "CA /%", pch = 18, xlim = c(0, xmax))
```

```{r, echo = TRUE}
# Put in Weibull noise and see the new data frames
noise_fac = 1/50
noise_NTE1 = abs(rnorm(1001, sd = dose^(1/2)))
noise_NTE2 = abs(rnorm(1001, sd = dose^(1/2)))
noise_IDER = abs(rnorm(1001, sd = dose^(1/2)))
CA_NTE1_w = CA_NTE1 * (1 + noise_fac * noise_NTE1)
CA_NTE2_w = CA_NTE2 * (1 + noise_fac * noise_NTE2)
CA_IDER_w = CA_IDER * (1 + noise_fac * noise_IDER)
plot(dose, rep(0, 1001), main = "Dose-Effect Relationship", xlab = "dose /cGy", ylab = "CA /%", col = "#FFFFFF", xlim = c(0, xmax), ylim = c(0, xmax*m2))
lines(dose, CA_NTE1_w, col = "red")
lines(dose, CA_NTE2_w, col = "green")
lines(dose, CA_IDER_w, col = "blue")
# Get artificial data from NTE2 (plus some noise)
art_data = CA_NTE2 * (1 + exp(-dose))
df = data.frame(dose, art_data)
df$CA_NTE1 = CA_NTE1
df$CA_NTE2 = CA_NTE2
df$CA_IDER = CA_IDER
legend(80, 3, c('NTE1', 'NTE2', 'IDER'), lty = c(1,1), lwd = c(2, 2), col = c('red', 'green', 'blue'))
```

```{r, echo = TRUE}
# Construct modified data frame to consider circumstances only when d > d0
mod_df <- df[-seq(1, 10*E/m1 + 1, 1), ]
# nls method to get the parameters needed (m1, m2, E, alpha; Y0 fixed) for NTE2 model
NTE2_model = nlsLM(art_data ~ Y0 + f_NTE2(dose, m1, m2, E), data = mod_df, start = list(m1 = 1, m2 = 0.1, E = 1), weights = noise_NTE2[(10*E/m1 + 2):1001])
coef(NTE2_model)
vcov(NTE2_model)
summary(NTE2_model, cor = TRUE)
# Now try to fit NTE1 model with the artificial data
NTE1_model = nlsLM(art_data ~ Y0 + f_NTE1(dose, m1, m2, E), data = mod_df, start = list(m1 = 1, m2 = 0.1, E = 1), weights = noise_NTE1[(10*E/m1 + 2):1001])
coef(NTE1_model)
vcov(NTE1_model)
summary(NTE1_model, cor = TRUE)
```

```{r, echo = TRUE}
# L_square gives the squared residuals
L_square = function(f, m1, m2, E) {
  s = vector(length = 0)
  for (i in 1:length(mod_df[, 1])) {
    s = c(s, mod_df$art_data[i] - f(d = mod_df$dose[i], m1 = m1, m2 = m2, E = E))
  }
  return(s^2)
}
# Take m1, m2, E values from nls. 
L_NTE2 = L_square(f_NTE2, m1 = coef(NTE2_model)[1], m2 = coef(NTE2_model)[2], E = coef(NTE2_model)[3])
L_NTE1 = L_square(f_NTE1, m1 = coef(NTE1_model)[1], m2 = coef(NTE1_model)[2], E = coef(NTE1_model)[3])
# Derive residual squared sum
RSS_NTE1 = sum(L_NTE1)
RSS_NTE2 = sum(L_NTE2)
RSS_NTE1
RSS_NTE2
```

```{r, echo = TRUE}
# AIC and BIC calculation for Least Square Regression
AIC_f = function(RSS, k = 3, n = length(mod_df[, 1])) {
  n + n*log(2*pi) + n*log(RSS/n) + 2*(k+1)
}
BIC_f = function(RSS, k = 3, n = length(mod_df[, 1])) {
  n + n*log(2*pi) + n*log(RSS/n) + log(n)*(k+1)
}
NTE1_AIC = AIC_f(RSS = RSS_NTE1)
NTE2_AIC = AIC_f(RSS = RSS_NTE2)
NTE1_BIC = BIC_f(RSS = RSS_NTE1)
NTE2_BIC = BIC_f(RSS = RSS_NTE2)
ic_df = data.frame(AIC = c(NTE1_AIC, NTE2_AIC), BIC = c(NTE1_BIC, NTE2_BIC), row.names = c("NTE1 model", "NTE2 model"))
ic_df
```