---
title: "Julien's Reproduction"
author: "Julien YU"
date: "2017/9/14"
output: html_document
---

```{r, echo = TRUE}
library(ggplot2) # library for plotting
library(deSolve) # library for solving differential equations
library(gridExtra) # library for plotting
library(minpack.lm) # library for non-linear regression package
```

```{r, echo = TRUE}
# Cacao's Data for HZE's Effect on Chromosome Aberration
# Oxygen(9), Silicon(11), Titanium(9), Iron600(11), Iron450(8), Iron300(10)
Oxygen = data.frame(d = c(0, .0125, .02, .025, .05, .075, .1, .2, .4), 
                    CA = c(.24, 1.66, 2.43, 2.37, 1.16, 2.85, 2.58, 6.94, 6.91))

Si = data.frame(d = c(0, .02, .04, .06, .08, .1, .12, .2, .4, .8, 1.2), 
                    CA = c(.11, 1.26, 1.14, 1.58, 1.22, 1.89, 3.47, 4.6, 9.79, 27.01, 38.84))

Ti = data.frame(d = c(0,  0.02, .04, .06, .08, .1, .15, .3, .6), 
                   CA = c(0, 1.99, 1.88, 1.44, 2.67, 2.57, 2.50, 5.64, 11.19))

Fe600 = data.frame(d = c(0, .01, .02, .04, .06, .08, .1, .12, .2, .4, .8), 
                     CA = c(.13, .76, .99, 1.2, 1.74, 1.28, 1.2, 1.7, 3.02, 5.52, 12.42))

Fe450 = data.frame(d = c(0, .02, .04, .06, .08, .1, .2, .4), 
                   CA = c(0, .86, .6, .8, 1.22, 2.02, 2.3, 4.77))

Fe300 = data.frame(d = c(0, .005, .01,  0.02, .04, .07, .1, .2, .4, .8), 
                   CA = c(0.41, 1.23, 1.47, 1.22, .97, 1.46, 1.21, 4.38, 6.22, 13.6))

# L in keV/um; Z & Z.beta with no unit
param = data.frame(ion = c("O", "Si", "Ti", "Fe600", "Fe450", "Fe300"),
                   Z = c(8, 14, 22, 26, 26, 26), L = c(75, 100, 125, 175, 195, 240), 
                   Z.beta = c(595, 690, 770, 1075, 1245, 1585))
```

```{r, echo = TRUE}
# Contruct a Big Data Frame containing all 58 data spots
# Comment 1: Cacao's data shows some really weird patterns at zero dose. For Ti and Fe450 there is no effect (CA) at zero dose, but for Fe300 it is unexpectedly large. Should it be considered background radiation? Are all the experiments done under the same condition? 
big_df = rbind(Oxygen, Si, Ti, Fe600, Fe450, Fe300)
big_df$Z = rep(param$Z, times = c(9, 11, 9, 11, 8, 10))
big_df$Z.beta = rep(param$Z.beta, times = c(9, 11, 9, 11, 8, 10))
big_df$L = rep(param$L, times = c(9, 11, 9, 11, 8, 10))
big_df$ion = rep(param$ion, times = c(9, 11, 9, 11, 8, 10))
```

```{r, echo = TRUE}
# Comment 2: I am not sure how Dae gets this array of error. Are these also in Cacao's original article? Why does the so-called "error" come before regression estimation? Also, why are the errors all postive? Are all of them overestimation and none of them underestimation? 
big_df$error = c(0.24, 0.63, 0.77, 0.75, 0.52, 0.82, 0.78, 1.31, 1.59, 0.12, 0.05, 0.07, 0.56, 0.18, 0.60, 1.23, 1.60, 1.55, 4.27, 7.21, 0, 0.70, 0.66, 0.59, 0.80, 0.78, 0.48, 1.15, 2.39, 0.16, 0.38, 0.24, 0.21, 0.02, 0.37, 0.54, 0.17, 0.55, 1.75, 2.59, 0, 0.43, 0.34, 0.40, 0.50, 0.64, 0.73, 1.09, 0.29, 0.55, 0.60, 0.55, 0.49, 0.60, 0.54, 1.03, 1.22, 3.62)
big_df
```

```{r, echo = TRUE}
# Modification of the data frame to avoid zero dose points irrelevant to the main parameter estimation
modified_df = big_df[big_df$d != 0, ]
modified_df
```

```{r, echo = TRUE}
# Modification of effect (CA) and the error
# Comment 3: Dae seems to have set the upper and lower "error bar" for each data point, using the error array we've seen before. Error bars are shown in A2.3, A2.4 and A2.5. However, what is the use? (Note that the "error bars" are not confidence intervals)
modified_df$CA = modified_df$CA*0.01
modified_df$error = modified_df$error*0.01
big_df$CA = big_df$CA * 0.01
big_df$error = big_df$error * 0.01
big_df$errorbar_lower = big_df$CA - big_df$error
big_df$errorbar_upper = big_df$CA + big_df$error
```

```{r, echo = TRUE}
# NTE1 function is based on page 16-17 of short11mainText (Equations 4-9) and page 4 of Supplementary3 (Adjustable parameters)
# 1-exp(-H)~1 since H is large; 1-exp(-d/d0)~1 since d0 is very small
# Average values of (adjustable parameters) are taken arbitrarily when constructing both functions. 
# Comment 4: I rephased the function a little bit to make it clearer. Two concerns: 1. the formula used here seems to calculate the total effect, not the NTE; 2. the background effect has average 0.00007, not 0.0017
NTE1_function = function(d, L, Z.beta, eta0 = 0.00011, eta1 = 0.007, sig0 = 6.12, kap = 796, bigF = 6.242, alpg = 0.041) {
0.0017 + eta0*L*exp(-eta1*L) + (bigF*(d/L))*(sig0*(1-exp(-Z.beta/kap))^2 + alpg*L/bigF*(1 - (1-exp(-Z.beta/kap))^2))
} 

# NTE2 function is based on the same source of information as NTE1 function. 
# Comment 5: H = FA = 1011.2*(d/L); why does Dae use "exp(-(1011.2*(d/L)))" as a rescaling factor between NTE and TE? 
NTE2_function = function(d, L, Z.beta, eta0 = 0.00047, eta1 = 0.011, sig0 = 6.75, kap = 590, bigF = 6.242, alpg = 0.041) {
0.0017 + eta0*L*exp(-eta1*L)*exp(-(1011.2*(d/L))) + (bigF*(d/L))*(1-exp(-(1011.2*(d/L))))*(sig0*(1-exp(-Z.beta/kap))^2 + alpg*L/bigF*(1 - (1-exp(-Z.beta/kap))^2))
} 
```

```{r, echo = TRUE}
# Proposed IDER Function. Still based on the same source of information as NTE1 & NTE2 function. 
IDER = function(d, L, Z.beta, eta0, eta1, sig0, kap, bigF = 6.242, alpg = 0.041) {
  P = (1-exp(-Z.beta/kap))^2
  sig = sig0*P + alpg*L/bigF*(1-P)
  eta = eta0*L*exp(-eta1*L)
  sig*bigF*d/L*(1-exp(-1011.2*d/L)) + eta*(1-exp(-10^5*d))
} 
```

```{r, echo = TRUE}
# Dae applied "nlsLM()" here to do the nonlinear least-square estimation (on 52 data spots excluding the zero dose situations). 
# Comment 6: I made some minor changes to the start of the list, which may let the resulting coefficients be more precise. The "weights" argument applied the inverse-quadratic function of (modified) errors: I need to know the reasoning behind this. Also, again, where does the "error" array come from? 
IDER_model = nlsLM(CA ~ IDER(d, L, Z.beta, eta0, eta1, sig0, kap), data = modified_df, start = list(eta0 = 0.00015, eta1 = 0.0035, sig0 = 4.2, kap = 469), weights = (1/(modified_df$error)^2))
coef(IDER_model)
vcov(IDER_model)
summary(IDER_model, cor = TRUE)
```

```{r, echo = TRUE}
# L_function gives the squared residuals of all 52 data spots for a particular function. I really like this chunk of code.
# "eta0 = 1.604215e-04, eta1 = 3.694551e-03, sig0 = 4.160713e+00, kap = 4.675690e+02" is derived from the coef() function of the previous chunk. 
L_function = function(func, eta0, eta1, sig0, kap){
  a = vector(length = 0)
  for (i in 1:length(modified_df[, 1])){
    a = c(a, modified_df$CA[i] - func(d = modified_df$d[i], L = modified_df$L[i], Z.beta = modified_df$Z.beta[i], eta0 = eta0, eta1 = eta1, sig0 = sig0, kap = kap))
  }
  return(a^2)
}
L_NTE1 = L_function(NTE1_function, eta0 = 0.00011, eta1 = 0.007, sig0 = 6.12, kap = 796)
L_NTE2 = L_function(NTE2_function, eta0 = 0.00047, eta1 = 0.011, sig0 = 6.75, kap = 590)
L_IDER = L_function(IDER, eta0 = 1.604215e-04, eta1 = 3.694551e-03, sig0 = 4.160713e+00, kap = 4.675690e+02)
```

```{r, echo = TRUE}
# Dae's original comments: since all models used in our NASA report and 16Cacao's are weighted least square regression, we will weight it with our weights to get the WRSS (weighted residual squared sum).
# Again, I want to know the logic behind this equation: weight of data spot = "its (modified) error"^(1/2)
WRSS_NTE1 = sum((1/modified_df$error^2)*L_NTE1)/52
WRSS_NTE2 = sum((1/modified_df$error^2)*L_NTE2)/52
WRSS_IDER = sum((1/modified_df$error^2)*L_IDER)/52
```

```{r, echo = TRUE}
# Dae applied the definition of AIC and BIC calculation for weighted least square regression. Double checked and agreed by Julien.
# Comment 7 (final comment): this chunk that constructs AIC and BIC seems OK to me. Due to the minor change I made in Comment 6, the AIC&BIC of NTE1&NTE2 appear to be a bit greater than in Dae's Code. Fortunately, the AIC&BIC of IDER remain almost the same, which symbolizes the effectiveness of the IDER model to a greater extent. 
AIC_function = function(RSS, k = 4, n = length(modified_df[, 1])) {
  n + n*log(2*pi) + n*log(RSS) + 2*(k+1)
}
BIC_function = function(RSS, k = 4, n = length(modified_df[, 1])) {
  n + n*log(2*pi) + n*log(RSS) + log(n)*(k+1)
}
NTE1_AIC = AIC_function(RSS = WRSS_NTE1)
NTE2_AIC = AIC_function(RSS = WRSS_NTE2)
IDER_AIC = AIC_function(RSS = WRSS_IDER)
NTE1_BIC = BIC_function(RSS = WRSS_NTE1)
NTE2_BIC = BIC_function(RSS = WRSS_NTE2)
IDER_BIC = BIC_function(RSS = WRSS_IDER)
information_critera_df = data.frame(AIC = c(NTE1_AIC, NTE2_AIC, IDER_AIC), BIC = c(NTE1_BIC, NTE2_BIC, IDER_BIC), row.names = c("NTE1 model", "NTE2 model", "IDER model"))
information_critera_df
```